// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostAdminLoginOKCode is the HTTP code returned for type PostAdminLoginOK
const PostAdminLoginOKCode int = 200

/*PostAdminLoginOK post admin login o k

swagger:response postAdminLoginOK
*/
type PostAdminLoginOK struct {

	/*
	  In: Body
	*/
	Payload *PostAdminLoginOKBody `json:"body,omitempty"`
}

// NewPostAdminLoginOK creates PostAdminLoginOK with default headers values
func NewPostAdminLoginOK() *PostAdminLoginOK {

	return &PostAdminLoginOK{}
}

// WithPayload adds the payload to the post admin login o k response
func (o *PostAdminLoginOK) WithPayload(payload *PostAdminLoginOKBody) *PostAdminLoginOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post admin login o k response
func (o *PostAdminLoginOK) SetPayload(payload *PostAdminLoginOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAdminLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAdminLoginBadRequestCode is the HTTP code returned for type PostAdminLoginBadRequest
const PostAdminLoginBadRequestCode int = 400

/*PostAdminLoginBadRequest Bad Request

swagger:response postAdminLoginBadRequest
*/
type PostAdminLoginBadRequest struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewPostAdminLoginBadRequest creates PostAdminLoginBadRequest with default headers values
func NewPostAdminLoginBadRequest() *PostAdminLoginBadRequest {

	return &PostAdminLoginBadRequest{}
}

// WithPayload adds the payload to the post admin login bad request response
func (o *PostAdminLoginBadRequest) WithPayload(payload interface{}) *PostAdminLoginBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post admin login bad request response
func (o *PostAdminLoginBadRequest) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAdminLoginBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostAdminLoginUnauthorizedCode is the HTTP code returned for type PostAdminLoginUnauthorized
const PostAdminLoginUnauthorizedCode int = 401

/*PostAdminLoginUnauthorized post admin login unauthorized

swagger:response postAdminLoginUnauthorized
*/
type PostAdminLoginUnauthorized struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewPostAdminLoginUnauthorized creates PostAdminLoginUnauthorized with default headers values
func NewPostAdminLoginUnauthorized() *PostAdminLoginUnauthorized {

	return &PostAdminLoginUnauthorized{}
}

// WithPayload adds the payload to the post admin login unauthorized response
func (o *PostAdminLoginUnauthorized) WithPayload(payload interface{}) *PostAdminLoginUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post admin login unauthorized response
func (o *PostAdminLoginUnauthorized) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAdminLoginUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostAdminLoginInternalServerErrorCode is the HTTP code returned for type PostAdminLoginInternalServerError
const PostAdminLoginInternalServerErrorCode int = 500

/*PostAdminLoginInternalServerError post admin login internal server error

swagger:response postAdminLoginInternalServerError
*/
type PostAdminLoginInternalServerError struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewPostAdminLoginInternalServerError creates PostAdminLoginInternalServerError with default headers values
func NewPostAdminLoginInternalServerError() *PostAdminLoginInternalServerError {

	return &PostAdminLoginInternalServerError{}
}

// WithPayload adds the payload to the post admin login internal server error response
func (o *PostAdminLoginInternalServerError) WithPayload(payload interface{}) *PostAdminLoginInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post admin login internal server error response
func (o *PostAdminLoginInternalServerError) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAdminLoginInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
