// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "online-store",
    "version": "1.0"
  },
  "host": "localhost:9000",
  "basePath": "/api/v1",
  "paths": {
    "/admin/login": {
      "post": {
        "summary": "Login With Admin",
        "operationId": "post-admin-login",
        "parameters": [
          {
            "x-examples": {
              "Create User Bob Fellow": {
                "dateOfBirth": "1996-08-24",
                "email": "bob.fellow@gmail.com",
                "firstName": "Bob",
                "lastName": "Fellow"
              }
            },
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "loginId",
                "password"
              ],
              "properties": {
                "loginId": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User Created",
            "schema": {
              "type": "object",
              "required": [
                "token"
              ],
              "properties": {
                "token": {
                  "type": "string"
                }
              }
            },
            "examples": {
              "example-1": {
                "token": "string"
              }
            }
          },
          "401": {
            "description": "Email Already Taken",
            "schema": {
              "type": "null"
            }
          },
          "500": {
            "description": "Missing Required Information",
            "schema": {
              "type": "null"
            }
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "online-store",
    "version": "1.0"
  },
  "host": "localhost:9000",
  "basePath": "/api/v1",
  "paths": {
    "/admin/login": {
      "post": {
        "summary": "Login With Admin",
        "operationId": "post-admin-login",
        "parameters": [
          {
            "x-examples": {
              "Create User Bob Fellow": {
                "dateOfBirth": "1996-08-24",
                "email": "bob.fellow@gmail.com",
                "firstName": "Bob",
                "lastName": "Fellow"
              }
            },
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "loginId",
                "password"
              ],
              "properties": {
                "loginId": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User Created",
            "schema": {
              "type": "object",
              "required": [
                "token"
              ],
              "properties": {
                "token": {
                  "type": "string"
                }
              }
            },
            "examples": {
              "example-1": {
                "token": "string"
              }
            }
          },
          "401": {
            "description": "Email Already Taken",
            "schema": {
              "type": "null"
            }
          },
          "500": {
            "description": "Missing Required Information",
            "schema": {
              "type": "null"
            }
          }
        }
      }
    }
  }
}`))
}
