// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "online-store",
    "version": "1.0"
  },
  "host": "localhost:9000",
  "basePath": "/api/v1",
  "paths": {
    "/admin/login": {
      "post": {
        "description": "post ",
        "summary": "Login With Admin",
        "operationId": "post-admin-login",
        "parameters": [
          {
            "x-examples": {},
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "loginId",
                "password"
              ],
              "properties": {
                "loginId": {
                  "type": "string",
                  "minLength": 1
                },
                "password": {
                  "type": "string",
                  "minLength": 1
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "type": "object",
              "required": [
                "token"
              ],
              "properties": {
                "token": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "x-nullable": true
            }
          },
          "401": {
            "description": "",
            "schema": {
              "type": "null"
            }
          },
          "500": {
            "description": "",
            "schema": {
              "type": "null"
            }
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "online-store",
    "version": "1.0"
  },
  "host": "localhost:9000",
  "basePath": "/api/v1",
  "paths": {
    "/admin/login": {
      "post": {
        "description": "post ",
        "summary": "Login With Admin",
        "operationId": "post-admin-login",
        "parameters": [
          {
            "x-examples": {},
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "loginId",
                "password"
              ],
              "properties": {
                "loginId": {
                  "type": "string",
                  "minLength": 1
                },
                "password": {
                  "type": "string",
                  "minLength": 1
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "type": "object",
              "required": [
                "token"
              ],
              "properties": {
                "token": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "x-nullable": true
            }
          },
          "401": {
            "description": "",
            "schema": {
              "type": "null"
            }
          },
          "500": {
            "description": "",
            "schema": {
              "type": "null"
            }
          }
        }
      }
    }
  }
}`))
}
