#!/usr/bin/env bash

set -eu

cd "$(dirname "$(cd "$(dirname "${BASH_SOURCE:-$0}")" && pwd)")"

(cd packages/online-store-admin-ui && rm -rf node_modules node_modules_tmp)

docker-compose build admin-ui

./scripts/attach-admin-ui <<EOL
yarn
tar zcvf node_modules_tmp node_modules > /dev/null
EOL

cd packages/online-store-admin-ui

tar zxvf node_modules_tmp > /dev/null
rm -rf node_modules_tmp
